server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.100.128:3100/loki/api/v1/push

scrape_configs:
- job_name: nginx
  entry_parser: raw
  static_configs:
  - targets:
      - localhost
    labels:
      job: nginx
      host: nc-v3
      __path__: /var/log/nginx/*log

- job_name: NC_logs
  entry_parser: raw
  static_configs:
  - targets:
      - localhost
    labels:
      job: NC_logs
      host: nc-v3
      __path__: /var/www/nextcloud/data/*log
